import type { RPCOutput } from "@/client/rpc/client";

type SupportedLanguage = RPCOutput["syntax"]["supportedLanguages"][number];

// cspell:ignore abap, gdscript, glsl, haml, haxe, objc, styl
export const EXTENSION_MAP = {
  abap: "abap",
  ada: "ada",
  astro: "astro",
  bash: "bash",
  bat: "bat",
  c: "c",
  cc: "cpp",
  cjs: "javascript",
  clj: "clojure",
  cljs: "clojure",
  cmake: "cmake",
  coffee: "coffee",
  cpp: "cpp",
  cs: "csharp",
  css: "css",
  csv: "csv",
  cts: "typescript",
  cxx: "cpp",
  dart: "dart",
  diff: "diff",
  docker: "docker",
  dockerfile: "dockerfile",
  elm: "elm",
  env: "bash",
  erl: "erlang",
  ex: "elixir",
  exs: "elixir",
  fish: "fish",
  fs: "fsharp",
  fsx: "fsharp",
  gd: "gdscript",
  gleam: "gleam",
  glsl: "glsl",
  gml: "xml",
  go: "go",
  gql: "graphql",
  graphql: "graphql",
  groovy: "groovy",
  h: "c",
  haml: "haml",
  hbs: "handlebars",
  hpp: "cpp",
  hs: "haskell",
  htm: "html",
  html: "html",
  hx: "haxe",
  hxx: "cpp",
  ini: "ini",
  java: "java",
  jl: "julia",
  js: "javascript",
  json: "json",
  jsonc: "jsonc",
  jsx: "jsx",
  kml: "xml",
  kt: "kotlin",
  latex: "latex",
  less: "less",
  lisp: "lisp",
  lock: "json",
  lua: "lua",
  m: "matlab",
  makefile: "makefile",
  md: "markdown",
  mdx: "mdx",
  mjs: "javascript",
  ml: "ocaml",
  mts: "typescript",
  nim: "nim",
  nix: "nix",
  objc: "objective-c",
  pas: "pascal",
  patch: "diff",
  perl: "perl",
  php: "php",
  pl: "perl",
  properties: "ini",
  proto: "proto",
  ps1: "powershell",
  pug: "pug",
  py: "python",
  r: "r",
  rb: "ruby",
  rs: "rust",
  rss: "xml",
  sass: "sass",
  scala: "scala",
  scheme: "scheme",
  scss: "scss",
  sh: "bash",
  sol: "solidity",
  sql: "sql",
  styl: "stylus",
  svelte: "svelte",
  svg: "xml",
  swift: "swift",
  tcl: "tcl",
  tex: "latex",
  toml: "toml",
  ts: "typescript",
  tsx: "tsx",
  vb: "vb",
  vim: "vim",
  vue: "vue",
  wasm: "wasm",
  xhtml: "html",
  xml: "xml",
  yaml: "yaml",
  yml: "yaml",
  zig: "zig",
  zsh: "bash",
} as const satisfies Record<string, SupportedLanguage>;

export function getLanguageFromFilePath(
  filePath: string,
): SupportedLanguage | undefined {
  const ext = filePath.split(".").pop()?.toLowerCase();
  if (!ext) {
    return undefined;
  }

  return EXTENSION_MAP[ext as keyof typeof EXTENSION_MAP];
}

export function toSupportedLanguage(
  language: string,
  supportedLanguages: SupportedLanguage[],
): SupportedLanguage | undefined {
  return supportedLanguages.includes(language as SupportedLanguage)
    ? (language as SupportedLanguage)
    : undefined;
}
