packages:
  - packages/*
  - apps/*

allowBuilds:
  "@swc/core": true
  core-js: true
  tree-sitter-javascript: true
  unrs-resolver: true

catalog:
  "@orpc/client": ^1.12.2
  "@orpc/contract": ^1.12.2
  "@orpc/server": ^1.12.2
  "@orpc/shared": ^1.12.2
  "@orpc/tanstack-query": ^1.12.2
  "@types/node": 22.19.2
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^5.1.2
  ai: ^5.0.97
  better-auth: ^1.2.12
  hono: ^4.7.8
  lucide-react: ^0.525.0
  react: ^19.2.1
  react-dom: ^19.2.1
  typescript: 5.9.2
  typescript-result: ^3.5.2
  vite: ^7.2.7
  vitest: ^3.2.4
  zod: ^4.1.13

configDependencies:
  "@pnpm/plugin-trusted-deps": 0.2.0+sha512-jqiCC8kyrwOERwMWPo2RB1YlDMMS5WsPSA8Uwi3EXAYwyOSNtqKhrB9bs543JGUiz4yaA9h6nE3q98fG14AEyQ==

patchedDependencies:
  "@openrouter/ai-sdk-provider": patches/@openrouter__ai-sdk-provider.patch
  conf@14.0.0: patches/conf@14.0.0.patch

sideEffectsCache: false
