packages:
  - packages/*
  - apps/*

catalog:
  "@orpc/client": ^1.10.4
  "@orpc/contract": ^1.10.4
  "@orpc/openapi": ^1.10.4
  "@orpc/server": ^1.10.4
  "@orpc/tanstack-query": ^1.10.4
  "@orpc/zod": ^1.10.4
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^4.7.0
  ai: ^5.0.97
  better-auth: ^1.2.12
  hono: ^4.7.8
  lucide-react: ^0.525.0
  nanoid: ^5.1.5
  react: ^19.2.1
  react-dom: ^19.2.1
  typescript: 5.9.2
  typescript-result: ^3.5.2
  vite: ^7.1.3
  vitest: ^3.2.4
  wrangler: ^4.25.0
  zod: ^4.1.3

configDependencies:
  "@pnpm/plugin-trusted-deps": 0.1.0+sha512-OK05vSZpezQHcS7Y0T5A25QXDbBRtRq52s76eOkMgp9v8ifNrIR8pjIGqrUFUn0PwKLt2i+U1LPYB+RWi1xjaQ==

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - oxc-resolver
  - core-js
  - tree-sitter-javascript
  - unrs-resolver

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/plugin-trusted-deps/allow.json

patchedDependencies:
  conf@14.0.0: patches/conf@14.0.0.patch

sideEffectsCache: false
