/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolbarRouteImport } from './routes/toolbar'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SidebarRouteImport } from './routes/sidebar'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsFeaturesRouteImport } from './routes/settings/features'
import { Route as SettingsDebugRouteImport } from './routes/settings/debug'
import { Route as SettingsAdvancedRouteImport } from './routes/settings/advanced'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppReleaseNotesRouteImport } from './routes/_app/release-notes'
import { Route as AppNewTabRouteImport } from './routes/_app/new-tab'
import { Route as AppDebugRouteRouteImport } from './routes/_app/debug/route'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppEvalsIndexRouteImport } from './routes/_app/evals/index'
import { Route as AppDiscoverIndexRouteImport } from './routes/_app/discover/index'
import { Route as AppDebugIndexRouteImport } from './routes/_app/debug/index'
import { Route as AppEvalsRunRouteImport } from './routes/_app/evals/run'
import { Route as AppDebugComponentsRouteImport } from './routes/_app/debug/components'
import { Route as AppDebugColorsRouteImport } from './routes/_app/debug/colors'
import { Route as AppProjectsSubdomainIndexRouteImport } from './routes/_app/projects/$subdomain/index'
import { Route as AppDiscoverTemplatesIndexRouteImport } from './routes/_app/discover/templates/index'
import { Route as AppDiscoverAppsIndexRouteImport } from './routes/_app/discover/apps/index'
import { Route as AppDiscoverTemplatesFolderNameRouteImport } from './routes/_app/discover/templates/$folderName'
import { Route as AppDiscoverAppsFolderNameRouteImport } from './routes/_app/discover/apps/$folderName'

const ToolbarRoute = ToolbarRouteImport.update({
  id: '/toolbar',
  path: '/toolbar',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRoute = SidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFeaturesRoute = SettingsFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDebugRoute = SettingsDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReleaseNotesRoute = AppReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewTabRoute = AppNewTabRouteImport.update({
  id: '/new-tab',
  path: '/new-tab',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDebugRouteRoute = AppDebugRouteRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvalsIndexRoute = AppEvalsIndexRouteImport.update({
  id: '/evals/',
  path: '/evals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoverIndexRoute = AppDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDebugIndexRoute = AppDebugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDebugRouteRoute,
} as any)
const AppEvalsRunRoute = AppEvalsRunRouteImport.update({
  id: '/evals/run',
  path: '/evals/run',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDebugComponentsRoute = AppDebugComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppDebugRouteRoute,
} as any)
const AppDebugColorsRoute = AppDebugColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => AppDebugRouteRoute,
} as any)
const AppProjectsSubdomainIndexRoute =
  AppProjectsSubdomainIndexRouteImport.update({
    id: '/projects/$subdomain/',
    path: '/projects/$subdomain/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDiscoverTemplatesIndexRoute =
  AppDiscoverTemplatesIndexRouteImport.update({
    id: '/discover/templates/',
    path: '/discover/templates/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDiscoverAppsIndexRoute = AppDiscoverAppsIndexRouteImport.update({
  id: '/discover/apps/',
  path: '/discover/apps/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoverTemplatesFolderNameRoute =
  AppDiscoverTemplatesFolderNameRouteImport.update({
    id: '/discover/templates/$folderName',
    path: '/discover/templates/$folderName',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDiscoverAppsFolderNameRoute =
  AppDiscoverAppsFolderNameRouteImport.update({
    id: '/discover/apps/$folderName',
    path: '/discover/apps/$folderName',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/checkout': typeof CheckoutRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sidebar': typeof SidebarRoute
  '/subscribe': typeof SubscribeRoute
  '/toolbar': typeof ToolbarRoute
  '/debug': typeof AppDebugRouteRouteWithChildren
  '/new-tab': typeof AppNewTabRoute
  '/release-notes': typeof AppReleaseNotesRoute
  '/setup': typeof AppSetupRoute
  '/welcome': typeof AppWelcomeRoute
  '/login': typeof AuthLoginRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/debug': typeof SettingsDebugRoute
  '/settings/features': typeof SettingsFeaturesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/': typeof SettingsIndexRoute
  '/debug/colors': typeof AppDebugColorsRoute
  '/debug/components': typeof AppDebugComponentsRoute
  '/evals/run': typeof AppEvalsRunRoute
  '/debug/': typeof AppDebugIndexRoute
  '/discover': typeof AppDiscoverIndexRoute
  '/evals': typeof AppEvalsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/discover/apps/$folderName': typeof AppDiscoverAppsFolderNameRoute
  '/discover/templates/$folderName': typeof AppDiscoverTemplatesFolderNameRoute
  '/discover/apps': typeof AppDiscoverAppsIndexRoute
  '/discover/templates': typeof AppDiscoverTemplatesIndexRoute
  '/projects/$subdomain': typeof AppProjectsSubdomainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/checkout': typeof CheckoutRoute
  '/sidebar': typeof SidebarRoute
  '/subscribe': typeof SubscribeRoute
  '/toolbar': typeof ToolbarRoute
  '/new-tab': typeof AppNewTabRoute
  '/release-notes': typeof AppReleaseNotesRoute
  '/setup': typeof AppSetupRoute
  '/welcome': typeof AppWelcomeRoute
  '/login': typeof AuthLoginRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/debug': typeof SettingsDebugRoute
  '/settings/features': typeof SettingsFeaturesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings': typeof SettingsIndexRoute
  '/debug/colors': typeof AppDebugColorsRoute
  '/debug/components': typeof AppDebugComponentsRoute
  '/evals/run': typeof AppEvalsRunRoute
  '/debug': typeof AppDebugIndexRoute
  '/discover': typeof AppDiscoverIndexRoute
  '/evals': typeof AppEvalsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/discover/apps/$folderName': typeof AppDiscoverAppsFolderNameRoute
  '/discover/templates/$folderName': typeof AppDiscoverTemplatesFolderNameRoute
  '/discover/apps': typeof AppDiscoverAppsIndexRoute
  '/discover/templates': typeof AppDiscoverTemplatesIndexRoute
  '/projects/$subdomain': typeof AppProjectsSubdomainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/browser': typeof BrowserRoute
  '/checkout': typeof CheckoutRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sidebar': typeof SidebarRoute
  '/subscribe': typeof SubscribeRoute
  '/toolbar': typeof ToolbarRoute
  '/_app/debug': typeof AppDebugRouteRouteWithChildren
  '/_app/new-tab': typeof AppNewTabRoute
  '/_app/release-notes': typeof AppReleaseNotesRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/debug': typeof SettingsDebugRoute
  '/settings/features': typeof SettingsFeaturesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/': typeof SettingsIndexRoute
  '/_app/debug/colors': typeof AppDebugColorsRoute
  '/_app/debug/components': typeof AppDebugComponentsRoute
  '/_app/evals/run': typeof AppEvalsRunRoute
  '/_app/debug/': typeof AppDebugIndexRoute
  '/_app/discover/': typeof AppDiscoverIndexRoute
  '/_app/evals/': typeof AppEvalsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/discover/apps/$folderName': typeof AppDiscoverAppsFolderNameRoute
  '/_app/discover/templates/$folderName': typeof AppDiscoverTemplatesFolderNameRoute
  '/_app/discover/apps/': typeof AppDiscoverAppsIndexRoute
  '/_app/discover/templates/': typeof AppDiscoverTemplatesIndexRoute
  '/_app/projects/$subdomain/': typeof AppProjectsSubdomainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browser'
    | '/checkout'
    | '/settings'
    | '/sidebar'
    | '/subscribe'
    | '/toolbar'
    | '/debug'
    | '/new-tab'
    | '/release-notes'
    | '/setup'
    | '/welcome'
    | '/login'
    | '/settings/advanced'
    | '/settings/debug'
    | '/settings/features'
    | '/settings/providers'
    | '/settings/'
    | '/debug/colors'
    | '/debug/components'
    | '/evals/run'
    | '/debug/'
    | '/discover'
    | '/evals'
    | '/projects'
    | '/discover/apps/$folderName'
    | '/discover/templates/$folderName'
    | '/discover/apps'
    | '/discover/templates'
    | '/projects/$subdomain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browser'
    | '/checkout'
    | '/sidebar'
    | '/subscribe'
    | '/toolbar'
    | '/new-tab'
    | '/release-notes'
    | '/setup'
    | '/welcome'
    | '/login'
    | '/settings/advanced'
    | '/settings/debug'
    | '/settings/features'
    | '/settings/providers'
    | '/settings'
    | '/debug/colors'
    | '/debug/components'
    | '/evals/run'
    | '/debug'
    | '/discover'
    | '/evals'
    | '/projects'
    | '/discover/apps/$folderName'
    | '/discover/templates/$folderName'
    | '/discover/apps'
    | '/discover/templates'
    | '/projects/$subdomain'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/browser'
    | '/checkout'
    | '/settings'
    | '/sidebar'
    | '/subscribe'
    | '/toolbar'
    | '/_app/debug'
    | '/_app/new-tab'
    | '/_app/release-notes'
    | '/_app/setup'
    | '/_app/welcome'
    | '/_auth/login'
    | '/settings/advanced'
    | '/settings/debug'
    | '/settings/features'
    | '/settings/providers'
    | '/settings/'
    | '/_app/debug/colors'
    | '/_app/debug/components'
    | '/_app/evals/run'
    | '/_app/debug/'
    | '/_app/discover/'
    | '/_app/evals/'
    | '/_app/projects/'
    | '/_app/discover/apps/$folderName'
    | '/_app/discover/templates/$folderName'
    | '/_app/discover/apps/'
    | '/_app/discover/templates/'
    | '/_app/projects/$subdomain/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  BrowserRoute: typeof BrowserRoute
  CheckoutRoute: typeof CheckoutRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SidebarRoute: typeof SidebarRoute
  SubscribeRoute: typeof SubscribeRoute
  ToolbarRoute: typeof ToolbarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolbar': {
      id: '/toolbar'
      path: '/toolbar'
      fullPath: '/toolbar'
      preLoaderRoute: typeof ToolbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidebar': {
      id: '/sidebar'
      path: '/sidebar'
      fullPath: '/sidebar'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/features': {
      id: '/settings/features'
      path: '/features'
      fullPath: '/settings/features'
      preLoaderRoute: typeof SettingsFeaturesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/debug': {
      id: '/settings/debug'
      path: '/debug'
      fullPath: '/settings/debug'
      preLoaderRoute: typeof SettingsDebugRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/release-notes': {
      id: '/_app/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof AppReleaseNotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/new-tab': {
      id: '/_app/new-tab'
      path: '/new-tab'
      fullPath: '/new-tab'
      preLoaderRoute: typeof AppNewTabRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/debug': {
      id: '/_app/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AppDebugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/evals/': {
      id: '/_app/evals/'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof AppEvalsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover/': {
      id: '/_app/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/debug/': {
      id: '/_app/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof AppDebugIndexRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/_app/evals/run': {
      id: '/_app/evals/run'
      path: '/evals/run'
      fullPath: '/evals/run'
      preLoaderRoute: typeof AppEvalsRunRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/debug/components': {
      id: '/_app/debug/components'
      path: '/components'
      fullPath: '/debug/components'
      preLoaderRoute: typeof AppDebugComponentsRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/_app/debug/colors': {
      id: '/_app/debug/colors'
      path: '/colors'
      fullPath: '/debug/colors'
      preLoaderRoute: typeof AppDebugColorsRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/_app/projects/$subdomain/': {
      id: '/_app/projects/$subdomain/'
      path: '/projects/$subdomain'
      fullPath: '/projects/$subdomain'
      preLoaderRoute: typeof AppProjectsSubdomainIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover/templates/': {
      id: '/_app/discover/templates/'
      path: '/discover/templates'
      fullPath: '/discover/templates'
      preLoaderRoute: typeof AppDiscoverTemplatesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover/apps/': {
      id: '/_app/discover/apps/'
      path: '/discover/apps'
      fullPath: '/discover/apps'
      preLoaderRoute: typeof AppDiscoverAppsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover/templates/$folderName': {
      id: '/_app/discover/templates/$folderName'
      path: '/discover/templates/$folderName'
      fullPath: '/discover/templates/$folderName'
      preLoaderRoute: typeof AppDiscoverTemplatesFolderNameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover/apps/$folderName': {
      id: '/_app/discover/apps/$folderName'
      path: '/discover/apps/$folderName'
      fullPath: '/discover/apps/$folderName'
      preLoaderRoute: typeof AppDiscoverAppsFolderNameRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppDebugRouteRouteChildren {
  AppDebugColorsRoute: typeof AppDebugColorsRoute
  AppDebugComponentsRoute: typeof AppDebugComponentsRoute
  AppDebugIndexRoute: typeof AppDebugIndexRoute
}

const AppDebugRouteRouteChildren: AppDebugRouteRouteChildren = {
  AppDebugColorsRoute: AppDebugColorsRoute,
  AppDebugComponentsRoute: AppDebugComponentsRoute,
  AppDebugIndexRoute: AppDebugIndexRoute,
}

const AppDebugRouteRouteWithChildren = AppDebugRouteRoute._addFileChildren(
  AppDebugRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDebugRouteRoute: typeof AppDebugRouteRouteWithChildren
  AppNewTabRoute: typeof AppNewTabRoute
  AppReleaseNotesRoute: typeof AppReleaseNotesRoute
  AppSetupRoute: typeof AppSetupRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppEvalsRunRoute: typeof AppEvalsRunRoute
  AppDiscoverIndexRoute: typeof AppDiscoverIndexRoute
  AppEvalsIndexRoute: typeof AppEvalsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppDiscoverAppsFolderNameRoute: typeof AppDiscoverAppsFolderNameRoute
  AppDiscoverTemplatesFolderNameRoute: typeof AppDiscoverTemplatesFolderNameRoute
  AppDiscoverAppsIndexRoute: typeof AppDiscoverAppsIndexRoute
  AppDiscoverTemplatesIndexRoute: typeof AppDiscoverTemplatesIndexRoute
  AppProjectsSubdomainIndexRoute: typeof AppProjectsSubdomainIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDebugRouteRoute: AppDebugRouteRouteWithChildren,
  AppNewTabRoute: AppNewTabRoute,
  AppReleaseNotesRoute: AppReleaseNotesRoute,
  AppSetupRoute: AppSetupRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppEvalsRunRoute: AppEvalsRunRoute,
  AppDiscoverIndexRoute: AppDiscoverIndexRoute,
  AppEvalsIndexRoute: AppEvalsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppDiscoverAppsFolderNameRoute: AppDiscoverAppsFolderNameRoute,
  AppDiscoverTemplatesFolderNameRoute: AppDiscoverTemplatesFolderNameRoute,
  AppDiscoverAppsIndexRoute: AppDiscoverAppsIndexRoute,
  AppDiscoverTemplatesIndexRoute: AppDiscoverTemplatesIndexRoute,
  AppProjectsSubdomainIndexRoute: AppProjectsSubdomainIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsDebugRoute: typeof SettingsDebugRoute
  SettingsFeaturesRoute: typeof SettingsFeaturesRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsDebugRoute: SettingsDebugRoute,
  SettingsFeaturesRoute: SettingsFeaturesRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  BrowserRoute: BrowserRoute,
  CheckoutRoute: CheckoutRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SidebarRoute: SidebarRoute,
  SubscribeRoute: SubscribeRoute,
  ToolbarRoute: ToolbarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
