import { QuestsLogoIcon } from "@quests/components/logo";
import { type IconName } from "@quests/shared/icons";
import {
  Activity,
  AlarmClock,
  Apple,
  AppWindow,
  AppWindowMac,
  Barcode,
  BatteryFull,
  Bell,
  Bookmark,
  Box,
  Briefcase,
  Calculator,
  Calendar,
  Camera,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  Clipboard,
  Cloud,
  CloudDownload,
  CloudUpload,
  Cog,
  Compass,
  CreditCard,
  Crown,
  Download,
  Dumbbell,
  Edit,
  File,
  FileStack,
  FileText,
  Flashlight,
  FlaskConical,
  Folder,
  Gem,
  Globe,
  GlobeLock,
  Grid,
  Heart,
  Home,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Library,
  List,
  Lock,
  LogIn,
  LogOut,
  type LucideIcon,
  Mail,
  Map,
  MapPin,
  MapPlus,
  Menu,
  MessageCircle,
  MessageSquare,
  Monitor,
  Moon,
  Package,
  PanelsTopLeft,
  Pen,
  Pencil,
  Phone,
  Scan,
  Search,
  Settings,
  ShoppingCart,
  Smartphone,
  Sparkles,
  SquareDashed,
  Star,
  Sun,
  Tablet,
  Telescope,
  Terminal,
  Tv,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserLock,
  UserPlus,
  UserRound,
  UserRoundPlus,
  Users,
  UserSearch,
  View,
  Wallet,
  Wifi,
  X,
  Zap,
} from "lucide-react";

export const IconMap: Record<IconName, LucideIcon> = {
  activity: Activity,
  "alarm-clock": AlarmClock,
  "app-window": AppWindow,
  "app-window-mac": AppWindowMac,
  apple: Apple,
  barcode: Barcode,
  "battery-full": BatteryFull,
  bell: Bell,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  check: Check,
  clipboard: Clipboard,
  cloud: Cloud,
  "cloud-download": CloudDownload,
  "cloud-upload": CloudUpload,
  cog: Cog,
  compass: Compass,
  "credit-card": CreditCard,
  crown: Crown,
  download: Download,
  dumbbell: Dumbbell,
  edit: Edit,
  file: File,
  "file-stack": FileStack,
  "file-text": FileText,
  flashlight: Flashlight,
  "flask-conical": FlaskConical,
  folder: Folder,
  gem: Gem,
  globe: Globe,
  "globe-lock": GlobeLock,
  grid: Grid,
  heart: Heart,
  home: Home,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  library: Library,
  list: List,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  "map-plus": MapPlus,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  monitor: Monitor,
  moon: Moon,
  package: Package,
  "panels-top-left": PanelsTopLeft,
  pen: Pen,
  pencil: Pencil,
  phone: Phone,
  quests: QuestsLogoIcon,
  scan: Scan,
  search: Search,
  settings: Settings,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  "square-dashed": SquareDashed,
  star: Star,
  sun: Sun,
  tablet: Tablet,
  telescope: Telescope,
  terminal: Terminal,
  tv: Tv,
  unlock: Unlock,
  upload: Upload,
  user: User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "user-lock": UserLock,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-round-plus": UserRoundPlus,
  "user-search": UserSearch,
  users: Users,
  view: View,
  wallet: Wallet,
  wifi: Wifi,
  x: X,
  zap: Zap,
} as const;
