env:
  CI: "true"
  DO_NOT_TRACK: "1"
  NODE_OPTIONS: "--max_old_space_size=4096"
jobs:
  check:
    name: Check and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive # Some tests use the registry
          # A fine-grained GitHub personal access token is required to checkout submodules
          # https://github.com/actions/checkout/issues/287
          # Permissions required:
          # - Repository access to quests-org/quests & quests-org/registry
          # - Read access to "Contents" and "Metadata"
          # - Read/Write access to actions and workflows
          token: ${{ secrets.CHECKOUT_ACCESS_TOKEN }}
      - uses: ./.github/actions/setup-ripgrep-cache
      - uses: ./.github/actions/prepare
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: rharkor/caching-for-turbo@v2.3.11
      - run: pnpm check-and-test

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
